# Generated by Django 2.2 on 2019-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
        ),
        migrations.RenameField(
            model_name='debts',
            old_name='student_debt',
            new_name='last_payment_amount',
        ),
        migrations.AddField(
            model_name='debts',
            name='minimum_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='debts',
            name='outstanding_amount_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='debts',
            name='outstanding_amount_principle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
