# Generated by Django 2.2.4 on 2019-12-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_bill_billdestination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='pay_to_account',
        ),
    ]
