# Generated by Django 2.2.4 on 2019-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agree_to_receive_emails',
            field=models.BooleanField(default=False),
        ),
    ]
