# Generated by Django 2.2.4 on 2019-10-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191024_1709'),
        ('users', '0004_auto_20191025_1743'),
    ]

    operations = [
    ]
