# Generated by Django 2.2.4 on 2020-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20191030_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institutions_connectable',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
