# Generated by Django 2.2.4 on 2020-01-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200107_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
