# Generated by Django 2.2.4 on 2019-08-28 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_userinstitution_plaid_id'),
        ('accounts', '0018_transactioncategory_plaid_id'),
        ('investments', '0002_auto_20190821_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_id', models.CharField(max_length=38)),
                ('isin', models.CharField(blank=True, default=None, max_length=38, null=True)),
                ('sedol', models.CharField(blank=True, default=None, max_length=38, null=True)),
                ('cusip', models.CharField(blank=True, default=None, max_length=38, null=True)),
                ('ticker_symbol', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('is_cash_equivalent', models.BooleanField(default=False)),
                ('close_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('close_price_as_of', models.DateField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Currency')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.SecurityType')),
                ('user_institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.UserInstitution')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_id', models.CharField(max_length=38)),
                ('institution_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('institution_price_as_of', models.DateField(blank=True, default=None, null=True)),
                ('institution_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Currency')),
                ('user_institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.UserInstitution')),
            ],
        ),
    ]
