# Generated by Django 2.2.4 on 2019-08-30 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_userinstitution_plaid_id'),
        ('investments', '0003_holding_security_securitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='holding',
            name='plaid_id',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='user_institution',
        ),
        migrations.RemoveField(
            model_name='security',
            name='plaid_id',
        ),
        migrations.RemoveField(
            model_name='security',
            name='user_institution',
        ),
        migrations.CreateModel(
            name='SecurityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_id', models.CharField(max_length=38)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.UserInstitution')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_id', models.CharField(max_length=38)),
                ('cancel_transaction_id', models.CharField(blank=True, default=None, max_length=38, null=True)),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('security_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.SecurityItem')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.TransactionType')),
            ],
        ),
        migrations.AddField(
            model_name='holding',
            name='security_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.SecurityItem'),
        ),
        migrations.AddField(
            model_name='security',
            name='security_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.SecurityItem'),
        ),
    ]
