# Generated by Django 2.2.4 on 2019-08-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_auto_20190831_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investments',
        ),
    ]
