# Generated by Django 2.2.4 on 2019-08-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_transactioncategory_plaid_id'),
        ('investments', '0005_delete_investments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holding',
            new_name='UserHolding',
        ),
        migrations.RenameModel(
            old_name='Security',
            new_name='UserSecurity',
        ),
    ]
