# Generated by Django 2.2.4 on 2019-08-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_auto_20190831_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersecurity',
            name='cusip',
        ),
        migrations.RemoveField(
            model_name='usersecurity',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='usersecurity',
            name='sedol',
        ),
        migrations.AddField(
            model_name='security',
            name='cusip',
            field=models.CharField(blank=True, default=None, max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='isin',
            field=models.CharField(blank=True, default=None, max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='sedol',
            field=models.CharField(blank=True, default=None, max_length=38, null=True),
        ),
    ]
