# Generated by Django 2.2.4 on 2019-08-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_auto_20190831_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='cost_basis',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='holding',
            name='institution_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='holding',
            name='institution_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
    ]
