# Generated by Django 2.2.4 on 2019-08-31 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_transactioncategory_plaid_id'),
        ('investments', '0013_auto_20190831_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
    ]
