# Generated by Django 2.2.4 on 2019-08-31 16:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('investments', '0015_investmenttransaction_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionType',
            new_name='InvestmentTransactionType',
        ),
        migrations.RemoveField(
            model_name='investmenttransaction',
            name='quantity',
        ),
    ]
