# Generated by Django 2.2.4 on 2019-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_auto_20190831_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=28),
        ),
    ]
