# Generated by Django 2.2.4 on 2019-08-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0017_investmenttransaction_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersecurity',
            name='plaid_id',
        ),
        migrations.AddField(
            model_name='security',
            name='plaid_id',
            field=models.CharField(blank=True, default=None, max_length=38, null=True),
        ),
    ]
