# Generated by Django 2.2.4 on 2019-09-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0018_auto_20190831_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmenttransaction',
            old_name='plaid_id',
            new_name='plaid_inv_transaction_id',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='plaid_id',
            new_name='plaid_security_id',
        ),
    ]
