# Generated by Django 2.2.4 on 2019-09-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0019_usersecuritysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecuritysnapshot',
            name='user_security',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.UserSecurity'),
        ),
    ]
