# Generated by Django 2.2.4 on 2019-09-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0019_auto_20190927_0253'),
        ('investments', '0021_auto_20190929_1433'),
    ]

    operations = [
    ]
