# Generated by Django 2.2.4 on 2019-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0022_merge_20190930_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='cost_basis',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='holdingsnapshot',
            name='cost_basis',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='usersecurity',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='usersecuritysnapshot',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=16, null=True),
        ),
    ]
