# Generated by Django 2.2.4 on 2019-11-14 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0023_auto_20191008_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('initial_principal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('time_in_years', models.IntegerField(blank=True, default=0, null=True)),
                ('input_amount_per_period', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('input_period_in_days', models.IntegerField(choices=[('Daily', 1), ('Weekly', 7), ('Biweekly', 14), ('Semi-monthly', 15), ('Monthly', 30), ('Yearly', 365)], default='Monthly')),
                ('times_compounded_per_year', models.IntegerField(choices=[('Daily', 365), ('Weekly', 52), ('Biweekly', 26), ('Semi-monthly', 24), ('Monthly', 12), ('Yearly', 1)], default='Monthly')),
            ],
        ),
    ]
