# Generated by Django 2.2.4 on 2019-11-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0025_mockinvestment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinvestment',
            name='input_period_in_days',
            field=models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly'), (15, 'Semi-monthly'), (30, 'Monthly'), (365, 'Yearly')], default=12),
        ),
        migrations.AlterField(
            model_name='mockinvestment',
            name='times_compounded_per_year',
            field=models.IntegerField(choices=[(365, 'Daily'), (52, 'Weekly'), (26, 'Biweekly'), (24, 'Semi-monthly'), (12, 'Monthly'), (1, 'Yearly')], default=12),
        ),
    ]
