# Generated by Django 2.2.4 on 2019-11-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0025_mockinvestment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockinvestment',
            old_name='input_amount_per_period',
            new_name='payment_amount_per_period',
        ),
        migrations.RemoveField(
            model_name='mockinvestment',
            name='input_period_in_days',
        ),
        migrations.AddField(
            model_name='mockinvestment',
            name='payment_period_in_days',
            field=models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly'), (15, 'Semi-monthly'), (30, 'Monthly'), (365, 'Yearly')], default=12),
        ),
        migrations.AlterField(
            model_name='mockinvestment',
            name='times_compounded_per_year',
            field=models.IntegerField(choices=[(365, 'Daily'), (52, 'Weekly'), (26, 'Biweekly'), (24, 'Semi-monthly'), (12, 'Monthly'), (1, 'Yearly')], default=12),
        ),
    ]
