# Generated by Django 2.2 on 2019-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_total', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
        ),
        migrations.RenameField(
            model_name='savings',
            old_name='balance',
            new_name='total_current_funds',
        ),
    ]
