# Generated by Django 2.2 on 2019-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gas_pay_per',
            new_name='miles_per',
        ),
        migrations.AddField(
            model_name='car',
            name='car_mpg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='car',
            name='miles_driven',
            field=models.IntegerField(default=0),
        ),
    ]
