# Generated by Django 2.2 on 2019-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0003_auto_20190821_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_average_housing', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('monthly_average_utilities', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('monthly_average_transportation', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('monthly_average_food', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('monthly_average_clothing', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('monthly_average_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('monthly_average_other', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
        ),
        migrations.AddField(
            model_name='expenditures',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
