# Generated by Django 2.2.3 on 2019-08-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0003_auto_20190808_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='display_period',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Year', max_length=7),
        ),
        migrations.AddField(
            model_name='food',
            name='display_period',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Year', max_length=7),
        ),
        migrations.AddField(
            model_name='housing',
            name='display_period',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Year', max_length=7),
        ),
        migrations.AddField(
            model_name='miscellaneous',
            name='display_period',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Year', max_length=7),
        ),
        migrations.AddField(
            model_name='utilities',
            name='display_period',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Year', max_length=7),
        ),
        migrations.AlterField(
            model_name='income',
            name='paycheck_period',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Weekly', max_length=7),
        ),
    ]
