# Generated by Django 2.2.3 on 2019-08-15 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expensetracker', '0004_auto_20190814_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='display_period',
        ),
        migrations.RemoveField(
            model_name='food',
            name='display_period',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='display_period',
        ),
        migrations.RemoveField(
            model_name='miscellaneous',
            name='display_period',
        ),
        migrations.RemoveField(
            model_name='utilities',
            name='display_period',
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', multiselectfield.db.fields.MultiSelectField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=19)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
