# Generated by Django 2.2.3 on 2019-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0005_auto_20190815_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='display',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='year', max_length=5),
        ),
    ]
