# Generated by Django 2.2.3 on 2019-08-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0007_auto_20190816_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='filing_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('married_separately', 'Married Separately'), ('head_of_household', 'Head of Household')], default='single', max_length=20),
        ),
    ]
