# Generated by Django 2.2.3 on 2019-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0010_auto_20190817_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='food',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='housing',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='miscellaneous',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='utilities',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
