# Generated by Django 2.2 on 2019-08-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0011_auto_20190817_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='display',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='year', max_length=5),
        ),
    ]
