# Generated by Django 2.2.4 on 2019-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0003_auto_20190928_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentloan',
            old_name='payments_remaining',
            new_name='pslf_payments_remaining',
        ),
    ]
