# Generated by Django 2.2.4 on 2019-09-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_accountsnapshot_date'),
        ('liabilities', '0004_auto_20190928_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='studentloan',
            name='account_id',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='studentloan',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
    ]
