# Generated by Django 2.2.4 on 2019-09-30 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_accountsnapshot_date'),
        ('institutions', '0002_userinstitution_plaid_id'),
        ('liabilities', '0005_auto_20190928_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoanSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('expected_payoff_date', models.DateField(blank=True, default=None, null=True)),
                ('guarantor', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('interest_rate_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_overdue', models.BooleanField(default=False)),
                ('last_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_payment_date', models.DateField(blank=True, default=None, null=True)),
                ('last_statement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_statement_issue_date', models.DateField(blank=True, default=None, null=True)),
                ('loan_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('minimum_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('next_payment_due_date', models.DateField(blank=True, default=None, null=True)),
                ('origination_date', models.DateField(blank=True, default=None, null=True)),
                ('origination_principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outstanding_interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_reference_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('estimated_pslf_eligibility_date', models.DateField(blank=True, default=None, null=True)),
                ('payments_made', models.IntegerField(default=0)),
                ('pslf_payments_remaining', models.IntegerField(default=0)),
                ('repayment_description', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('repayment_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('ytd_interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ytd_principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
                ('student_loan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liabilities.StudentLoan')),
                ('user_institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.UserInstitution')),
            ],
        ),
    ]
