# Generated by Django 2.2.4 on 2019-09-30 18:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_accountsnapshot_date'),
        ('institutions', '0002_userinstitution_plaid_id'),
        ('liabilities', '0006_studentloansnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_overdue', models.BooleanField(default=False)),
                ('last_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_payment_date', models.DateField(blank=True, default=None, null=True)),
                ('last_statement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_statement_issue_date', models.DateField(blank=True, default=None, null=True)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('minimum_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('next_payment_due_date', models.DateField(blank=True, default=None, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
                ('credit_card', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liabilities.CreditCard')),
                ('user_institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.UserInstitution')),
            ],
        ),
    ]
