# Generated by Django 2.2.4 on 2019-09-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0007_creditcardsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardsnapshot',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
