# Generated by Django 2.2.4 on 2019-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0009_auto_20191005_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='late_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True),
        ),
    ]
