# Generated by Django 2.2.4 on 2019-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0011_auto_20191008_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apr',
            name='apr_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='apr',
            name='balance_subject_to_apr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='apr',
            name='interest_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='last_statement_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='minimum_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardsnapshot',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardsnapshot',
            name='last_statement_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardsnapshot',
            name='minimum_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='is_overdue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='last_statement_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='minimum_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='origination_principal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='outstanding_interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='payments_made',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='pslf_payments_remaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='sequence_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='ytd_interest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloan',
            name='ytd_principal_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='is_overdue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='last_statement_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='minimum_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='origination_principal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='outstanding_interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='payments_made',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='pslf_payments_remaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='sequence_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='ytd_interest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentloansnapshot',
            name='ytd_principal_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
