# Generated by Django 2.2.4 on 2019-11-12 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liabilities', '0013_auto_20191105_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiabilityAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
