# Generated by Django 2.2.4 on 2019-11-12 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0014_liabilityanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilityanalysis',
            name='user',
        ),
        migrations.AddField(
            model_name='liabilityanalysis',
            name='student_loan',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='liabilities.StudentLoan'),
        ),
    ]
