# Generated by Django 2.2.4 on 2019-12-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0015_auto_20191112_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentloan',
            old_name='guarantor',
            new_name='guarantor_name',
        ),
        migrations.RenameField(
            model_name='studentloansnapshot',
            old_name='guarantor',
            new_name='guarantor_name',
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_name', models.CharField(default=None, max_length=128)),
                ('mailing_address', models.CharField(default=None, max_length=256)),
                ('home_address', models.CharField(default=None, max_length=256)),
                ('ach_account_number', models.CharField(max_length=32)),
                ('student_loan', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liabilities.StudentLoan')),
            ],
        ),
    ]
