# Generated by Django 2.2.4 on 2019-11-09 20:44

from django.db import migrations, models
import expenditures.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0004_auto_20191109_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=expenditures.models.Housing, max_length=100),
        ),
        migrations.AddField(
            model_name='housing',
            name='name',
            field=models.CharField(default='Housing', max_length=100),
        ),
    ]
