# Generated by Django 2.2.4 on 2019-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0005_auto_20191109_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='Car', max_length=100),
        ),
    ]
