# Generated by Django 2.2.4 on 2019-11-21 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenditures', '0006_auto_20191109_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('cost_per_pay_period', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('pay_to_account', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(default=None)),
                ('set_auto_pay', models.BooleanField(default=False)),
                ('payment_period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Weekly', max_length=7)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
