# Generated by Django 2.2.4 on 2019-11-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0007_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cost_per_pay_period',
        ),
    ]
