# Generated by Django 2.2.4 on 2019-12-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0008_remove_bill_cost_per_pay_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
