# Generated by Django 2.2.4 on 2019-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190825_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='sub_type',
            new_name='subtype',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='official_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
