# Generated by Django 2.2.4 on 2019-08-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190825_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='access_token',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
