# Generated by Django 2.2.4 on 2019-08-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190825_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserInstitution'),
        ),
    ]
