# Generated by Django 2.2.4 on 2019-08-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_remove_income_user_institution'),
        ('accounts', '0014_auto_20190825_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstitution',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='userinstitution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='UserInstitution',
        ),
    ]
