# Generated by Django 2.2.4 on 2019-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_transaction_transactioncategory_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='plaid_id',
            field=models.CharField(default=None, max_length=38),
        ),
    ]
