# Generated by Django 2.2.4 on 2019-09-14 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_transactioncategory_plaid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
            ],
        ),
    ]
