# Generated by Django 2.2.4 on 2019-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
