# Generated by Django 2.2.4 on 2019-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_accountsnapshot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncategory',
            old_name='plaid_id',
            new_name='plaid_category_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='uuid',
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='group',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='sub_category_1',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='sub_category_2',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='sub_category_3',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
