# Generated by Django 2.2.4 on 2019-10-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20191004_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='sub_category_2',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='sub_category_3',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
