# Generated by Django 2.2.4 on 2019-10-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20191004_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_bank_account_token',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
