# Generated by Django 2.2.4 on 2019-10-18 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_account_stripe_bank_account_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_user_institution', to='institutions.UserInstitution'),
        ),
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number_type', models.CharField(blank=True, choices=[('ach', 'ACH')], default=('ach', 'ACH'), max_length=128, null=True)),
                ('number_id', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('number_routing', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_number_to_account', to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
