# Generated by Django 2.2.4 on 2020-01-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20191018_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='account',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_number_to_account', to='accounts.Account'),
        ),
    ]
