# Generated by Django 2.2.4 on 2020-01-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200116_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_number_to_account', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='number_type',
            field=models.CharField(blank=True, choices=[('ach', 'ACH')], default=None, max_length=128, null=True),
        ),
    ]
