# Generated by Django 2.2.4 on 2020-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200116_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
