# Generated by Django 2.2 on 2019-08-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hornescalculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
    ]
