# Generated by Django 2.2 on 2019-08-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hornescalculator', '0002_remove_income_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
