# Generated by Django 2.2 on 2019-08-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='cost_of_tax',
            new_name='projected_yearly_income',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income_after_tax',
            new_name='projected_yearly_minus_tax',
        ),
        migrations.RemoveField(
            model_name='income',
            name='total_income',
        ),
    ]
