# Generated by Django 2.2.4 on 2019-08-25 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20190821_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('days', models.IntegerField(default=0)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='cost_of_taxes_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='income',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='last_year_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='income',
            name='last_year_income_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='income',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='projected_yearly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='income',
            name='projected_yearly_minus_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
