# Generated by Django 2.2.4 on 2019-08-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20190825_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='cost_of_taxes_paid',
            new_name='last_year_income_minus_tax',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='last_year_income',
            new_name='last_year_income_tax',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='projected_yearly_income',
            new_name='projected_yearly_income_before_tax',
        ),
        migrations.AddField(
            model_name='income',
            name='max_number_of_overlapping_income_streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='income',
            name='number_of_income_streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='income',
            name='projected_yearly_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='incomestream',
            name='income',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.Income'),
        ),
    ]
