# Generated by Django 2.2.4 on 2019-08-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_auto_20190825_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='last_year_income_tax',
            new_name='last_year_taxes',
        ),
    ]
