# Generated by Django 2.2.4 on 2019-08-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190825_2032'),
        ('income', '0005_auto_20190825_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.AddField(
            model_name='income',
            name='user_institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserInstitution'),
        ),
    ]
