# Generated by Django 2.2.4 on 2019-08-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('income', '0007_remove_income_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='user_institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.UserInstitution'),
        ),
    ]
