# Generated by Django 2.2.4 on 2020-04-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractStudentLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('payments_per_year', models.IntegerField(blank=True, default=12, null=True)),
            ],
        ),
    ]
