# Generated by Django 2.2.4 on 2019-08-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstitution',
            name='plaid_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
